data:
  SLANG: assets/slang.txt
  STOP: assets/stopwords.txt
  REPORT: assets/report.json

sqlite:
  LOCAL_SQLITE_DB: assets/archives.db
  FEED_TABLE_NAME: tweets

subscribe:
  - microsvuln
  - barbieauglend
  - 5aelo
  - mobilesecurity_
  - dao0x
  - peta909
  - zhaiyizhuo
  - azeria_labs
  - richinseattle
  - laosong
  - ICSEconf
  - malwareunicorn
  - herrcore
  - marcinguy
  - PLDI
  - aurelsec
  - sljrobin
  - nn_amon
  - vuly16
  - megabeets_
  - gN3mes1s
  - tiraniddo
  - campuscodi
  - reconmtl
  - K3vinLuSec
  - MalwareTechBlog
  - klotxl404
  - Fox0x01
  - Jackson_T
  - _L4ys
  - moarbugs
  - riusksk
  - usenix
  - 0x0aTang
  - verovaleros
  - kleesymex
  - hardik05
  - maldr0id
  - _xpn_
  - struppigel
  - FSecureLabs
  - hasherezade
  - gannimo
  - maddiestone
  - ahack_ru
  - IntezerLabs
  - patrickwardle
  - abatchy17
  - babyjess1ca_
  - AndreasZeller
  - bkth_
  - XenoKovah
  - b1ack0wl
  - seanhn
  - leonwxqian
  - domenuk
  - binitamshah
  - bellis1000
  - artem_i_baranov
  - TheHackersNews
  - JonathanAfek
  - moveax41h
  - ifsecure
  - badsectorlabs
  - S0rryMybad
  - NDSSSymposium
  - lorenc_dan
  - pinkflawd
  - FuzzingLabs
  - pkqzy888
  - ReversingLabs
  - gamozolabs
  - mboehme_
  - 0net0all
  - dwfault
  - keen_lab
  - acm_ccs
  - yongdaek
  - _longlu_
  - _jsoo_
  - yixue_zhao
  - ASPLOSConf
  - Digital_Cold
  - cxm95
  - _CPResearch_
  - christophetd
  - HaskRay
  - reyammer
  - scwuaptx
  - RedNagaSec
  - LinkCabin
  - _qaz_qaz
  - m417z
  - BinsecTool
  - chmodxx_
  - is_eqv